allowBuilds:
  '@parcel/watcher': set this to true or false
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  prisma: true
  unrs-resolver: set this to true or false

packages:
  - "."
